services:
  server:
    environment:
      DATABASE_URL: "postgres://postgres:password123@db"
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
  db:
    environment:
      POSTGRES_PASSWORD: password123
    image: postgres:alpine
    expose:
      - 5432
