services:
  server:
    environment:
      DATABASE_URL: 'postgres://postgres:password123@db'
      JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
    build:
      dockerfile: ./backend/Dockerfile
      # set context to repo root so that the data can be passed in
      context: ../
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
  db:
    environment:
      POSTGRES_PASSWORD: password123
    image: postgres:alpine
    expose:
      - 5432
