# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.1.3'

gem 'bootsnap', require: false
gem 'devise'
gem 'devise-jwt'
gem 'faraday'
gem 'http_accept_language'
gem 'jbuilder'
gem 'net-imap', '>= 0.5.6'
gem 'newrelic_rpm'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'pundit'
gem 'rack', '~> 2.2.11'
gem 'rack-cors', '~> 2.0'
gem 'rails', '~> 7.1.4'
gem 'rexml', '>= 3.3.9'
gem 'sendgrid-actionmailer'
gem 'sprockets-rails'
gem 'sucker_punch', '~> 3.0'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'pry'
  gem 'rspec-rails', '~> 6.0.0'
end

group :development do
  gem 'brakeman'
  gem 'bundle-audit'
  gem 'rubocop'
  gem 'rubocop-rails'
  gem 'smarter_csv'
  gem 'syntax_suggest'
  gem 'web-console'
end
