// export all the assignments in the database

module.exports = [
  {
    id: 1,
    group: "A1",
    surveyor_id: 1,
    homes: [
      {
        id: 1,
        home_id: 1,
        visit_order: 0,
        completed: true,
      },
      {
        id: 2,
        home_id: 2,
        visit_order: 1,
        completed: false,
      },
      {
        id: 3,
        home_id: 3,
        visit_order: 2,
        completed: false,
      },
      {
        id: 4,
        home_id: 4,
        visit_order: 3,
        completed: true,
      },
      {
        id: 5,
        home_id: 5,
        visit_order: 4,
        completed: true,
      },
      {
        id: 6,
        home_id: 6,
        visit_order: 5,
        completed: true,
      },
      {
        id: 7,
        home_id: 7,
        visit_order: 6,
        completed: false,
      },
      {
        id: 8,
        home_id: 8,
        visit_order: 7,
        completed: true,
      },
      {
        id: 9,
        home_id: 9,
        visit_order: 8,
        completed: true,
      },
      {
        id: 10,
        home_id: 10,
        visit_order: 9,
        completed: false,
      },
      {
        id: 11,
        home_id: 11,
        visit_order: 10,
        completed: true,
      },
      {
        id: 12,
        home_id: 12,
        visit_order: 11,
        completed: false,
      },
      {
        id: 13,
        home_id: 13,
        visit_order: 12,
        completed: false,
      },
      {
        id: 14,
        home_id: 14,
        visit_order: 13,
        completed: true,
      },
      {
        id: 15,
        home_id: 15,
        visit_order: 14,
        completed: true,
      },
      {
        id: 16,
        home_id: 16,
        visit_order: 15,
        completed: true,
      },
      {
        id: 17,
        home_id: 17,
        visit_order: 16,
        completed: true,
      },
      {
        id: 18,
        home_id: 18,
        visit_order: 17,
        completed: true,
      },
      {
        id: 19,
        home_id: 19,
        visit_order: 18,
        completed: true,
      },
      {
        id: 20,
        home_id: 20,
        visit_order: 19,
        completed: true,
      },
      {
        id: 21,
        home_id: 21,
        visit_order: 20,
        completed: true,
      },
      {
        id: 22,
        home_id: 22,
        visit_order: 21,
        completed: true,
      },
    ],
  },
  {
    id: 2,
    group: "A1",
    surveyor_id: 2,
    homes: [
      {
        id: 1,
        home_id: 23,
        visit_order: 0,
        completed: true,
      },
      {
        id: 2,
        home_id: 24,
        visit_order: 1,
        completed: false,
      },
      {
        id: 3,
        home_id: 25,
        visit_order: 2,
        completed: false,
      },
      {
        id: 4,
        home_id: 26,
        visit_order: 3,
        completed: true,
      },
      {
        id: 5,
        home_id: 27,
        visit_order: 4,
        completed: true,
      },
      {
        id: 6,
        home_id: 28,
        visit_order: 5,
        completed: true,
      },
      {
        id: 7,
        home_id: 29,
        visit_order: 6,
        completed: false,
      },
      {
        id: 8,
        home_id: 30,
        visit_order: 7,
        completed: true,
      },
      {
        id: 9,
        home_id: 31,
        visit_order: 8,
        completed: true,
      },
      {
        id: 10,
        home_id: 32,
        visit_order: 9,
        completed: false,
      },
      {
        id: 11,
        home_id: 33,
        visit_order: 10,
        completed: true,
      },
      {
        id: 12,
        home_id: 34,
        visit_order: 11,
        completed: false,
      },
      {
        id: 13,
        home_id: 35,
        visit_order: 12,
        completed: false,
      },
      {
        id: 14,
        home_id: 36,
        visit_order: 13,
        completed: true,
      },
      {
        id: 15,
        home_id: 37,
        visit_order: 14,
        completed: true,
      },
      {
        id: 16,
        home_id: 38,
        visit_order: 15,
        completed: true,
      },
      {
        id: 17,
        home_id: 39,
        visit_order: 16,
        completed: true,
      },
      {
        id: 18,
        home_id: 40,
        visit_order: 17,
        completed: true,
      },
      {
        id: 19,
        home_id: 41,
        visit_order: 18,
        completed: true,
      },
      {
        id: 20,
        home_id: 42,
        visit_order: 19,
        completed: true,
      },
      {
        id: 21,
        home_id: 43,
        visit_order: 20,
        completed: true,
      },
      {
        id: 22,
        home_id: 44,
        visit_order: 21,
        completed: true,
      },
    ],
  },
];
