require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/property_assessments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PropertyAssessment. As you add validations to PropertyAssessment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PropertyAssessment.create! valid_attributes
      get property_assessments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      property_assessment = PropertyAssessment.create! valid_attributes
      get property_assessment_url(property_assessment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_property_assessment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      property_assessment = PropertyAssessment.create! valid_attributes
      get edit_property_assessment_url(property_assessment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PropertyAssessment" do
        expect {
          post property_assessments_url, params: { property_assessment: valid_attributes }
        }.to change(PropertyAssessment, :count).by(1)
      end

      it "redirects to the created property_assessment" do
        post property_assessments_url, params: { property_assessment: valid_attributes }
        expect(response).to redirect_to(property_assessment_url(PropertyAssessment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PropertyAssessment" do
        expect {
          post property_assessments_url, params: { property_assessment: invalid_attributes }
        }.to change(PropertyAssessment, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post property_assessments_url, params: { property_assessment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested property_assessment" do
        property_assessment = PropertyAssessment.create! valid_attributes
        patch property_assessment_url(property_assessment), params: { property_assessment: new_attributes }
        property_assessment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the property_assessment" do
        property_assessment = PropertyAssessment.create! valid_attributes
        patch property_assessment_url(property_assessment), params: { property_assessment: new_attributes }
        property_assessment.reload
        expect(response).to redirect_to(property_assessment_url(property_assessment))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        property_assessment = PropertyAssessment.create! valid_attributes
        patch property_assessment_url(property_assessment), params: { property_assessment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested property_assessment" do
      property_assessment = PropertyAssessment.create! valid_attributes
      expect {
        delete property_assessment_url(property_assessment)
      }.to change(PropertyAssessment, :count).by(-1)
    end

    it "redirects to the property_assessments list" do
      property_assessment = PropertyAssessment.create! valid_attributes
      delete property_assessment_url(property_assessment)
      expect(response).to redirect_to(property_assessments_url)
    end
  end
end
