require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/survey_visits', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SurveyVisit. As you add validations to SurveyVisit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      SurveyVisit.create! valid_attributes
      get survey_visits_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      survey_visit = SurveyVisit.create! valid_attributes
      get survey_visit_url(survey_visit)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_survey_visit_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      survey_visit = SurveyVisit.create! valid_attributes
      get edit_survey_visit_url(survey_visit)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new SurveyVisit' do
        expect do
          post survey_visits_url, params: { survey_visit: valid_attributes }
        end.to change(SurveyVisit, :count).by(1)
      end

      it 'redirects to the created survey_visit' do
        post survey_visits_url, params: { survey_visit: valid_attributes }
        expect(response).to redirect_to(survey_visit_url(SurveyVisit.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new SurveyVisit' do
        expect do
          post survey_visits_url, params: { survey_visit: invalid_attributes }
        end.to change(SurveyVisit, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post survey_visits_url, params: { survey_visit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested survey_visit' do
        survey_visit = SurveyVisit.create! valid_attributes
        patch survey_visit_url(survey_visit), params: { survey_visit: new_attributes }
        survey_visit.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the survey_visit' do
        survey_visit = SurveyVisit.create! valid_attributes
        patch survey_visit_url(survey_visit), params: { survey_visit: new_attributes }
        survey_visit.reload
        expect(response).to redirect_to(survey_visit_url(survey_visit))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        survey_visit = SurveyVisit.create! valid_attributes
        patch survey_visit_url(survey_visit), params: { survey_visit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested survey_visit' do
      survey_visit = SurveyVisit.create! valid_attributes
      expect do
        delete survey_visit_url(survey_visit)
      end.to change(SurveyVisit, :count).by(-1)
    end

    it 'redirects to the survey_visits list' do
      survey_visit = SurveyVisit.create! valid_attributes
      delete survey_visit_url(survey_visit)
      expect(response).to redirect_to(survey_visits_url)
    end
  end
end
