# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/survey_answers', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SurveyAnswer. As you add validations to SurveyAnswer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      SurveyAnswer.create! valid_attributes
      get survey_answers_url, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      survey_answer = SurveyAnswer.create! valid_attributes
      get survey_answer_url(survey_answer), as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_survey_answer_url, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      survey_answer = SurveyAnswer.create! valid_attributes
      get edit_survey_answer_url(survey_answer), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new SurveyAnswer' do
        expect do
          post survey_answers_url, params: { survey_answer: valid_attributes }
        end.to change(SurveyAnswer, :count).by(1)
      end

      it 'redirects to the created survey_answer' do
        post survey_answers_url, params: { survey_answer: valid_attributes }
        expect(response).to redirect_to(survey_answer_url(SurveyAnswer.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new SurveyAnswer' do
        expect do
          post survey_answers_url, params: { survey_answer: invalid_attributes }
        end.to change(SurveyAnswer, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post survey_answers_url, params: { survey_answer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested survey_answer' do
        survey_answer = SurveyAnswer.create! valid_attributes
        patch survey_answer_url(survey_answer), params: { survey_answer: new_attributes }
        survey_answer.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the survey_answer' do
        survey_answer = SurveyAnswer.create! valid_attributes
        patch survey_answer_url(survey_answer), params: { survey_answer: new_attributes }
        survey_answer.reload
        expect(response).to redirect_to(survey_answer_url(survey_answer))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        survey_answer = SurveyAnswer.create! valid_attributes
        patch survey_answer_url(survey_answer), params: { survey_answer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested survey_answer' do
      survey_answer = SurveyAnswer.create! valid_attributes
      expect do
        delete survey_answer_url(survey_answer)
      end.to change(SurveyAnswer, :count).by(-1)
    end

    it 'redirects to the survey_answers list' do
      survey_answer = SurveyAnswer.create! valid_attributes
      delete survey_answer_url(survey_answer)
      expect(response).to redirect_to(survey_answers_url)
    end
  end
end
